global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'model-service'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
  
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']