global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'model_service'
    static_configs:
      - targets: ['172.18.211.68:8000']
    metrics_path: '/metrics'
  
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']